define(
	['./application/@dir', './primitive/button/@dir', './primitive/button/buttonBadge/@dir', './primitive/button/buttonCheckbox/@dir', './primitive/button/buttonFile/@dir', './control/@dir', './curtainManager/@dir', './curtainManager/curtainManagerRouterContent/@dir', './entry/@dir', './primitive/field/@dir', './primitive/field/fieldCheckbox/@dir', './form/@dir', './primitive/input/@dir',
		'./control/label/@dir', './primitive/link/@dir', './list/@dir', './list/listEditable/@dir', './panel/@dir', './primitive/@dir', './primitive/radio/@dir', './primitive/selectorBox/@dir', './primitive/selectorDropdown/@dir', './table/@dir', './tableEntry/@dir', './tableHandle/@dir', './tableHeader/@dir', './tableHeaderField/@dir',
		'./table/tableList/@dir', './tableListEntry/@dir', './tableHeader/tableListHeader/@dir', './tableListHeaderField/@dir', './tableTreeEntry/@dir', './tabs/@dir', './tabs/tabsRouterContent/@dir', './treeBranch/@dir', './treeBranch/tree/@dir', './treeBranch/tree/treeEditable/@dir', './windowManager/@dir', './windowManager/windowManagerRouterContent/@dir'],
	function(application, button, buttonBadge, buttonCheckbox, buttonFile, control, curtainManager, curtainManagerRouterContent, entry, field, fieldCheckbox, form, input, label, link, list, listEditable, panel, primitive, radio, selectorBox, selectorDropdown, table, tableEntry, tableHandle, tableHeader, tableHeaderField, tableList, tableListEntry, tableListHeader, tableListHeaderField, tableTreeEntry, tabs, tabsRouterContent, treeBranch, tree, treeEditable, windowManager, windowManagerRouterContent) {
		"use strict";

		return {
			application: application,
			button: button,
			buttonBadge: buttonBadge,
			buttonCheckbox: buttonCheckbox,
			buttonFile: buttonFile,
			control: control,
			curtainManager: curtainManager,
			curtainManagerRouterContent: curtainManagerRouterContent,
			entry: entry,
			field: field,
			fieldCheckbox: fieldCheckbox,
			form: form,
			input: input,
			label: label,
			link: link,
			list: list,
			listEditable: listEditable,
			panel: panel,
			primitive: primitive,
			radio: radio,
			selectorBox: selectorBox,
			selectorDropdown: selectorDropdown,
			table: table,
			tableEntry: tableEntry,
			tableHandle: tableHandle,
			tableHeader: tableHeader,
			tableHeaderField: tableHeaderField,
			tableList: tableList,
			tableListEntry: tableListEntry,
			tableListHeader: tableListHeader,
			tableListHeaderField: tableListHeaderField,
			tableTreeEntry: tableTreeEntry,
			tabs: tabs,
			tabsRouterContent: tabsRouterContent,
			tree: tree,
			treeBranch: treeBranch,
			treeEditable: treeEditable,
			windowManager: windowManager,
			windowManagerRouterContent: windowManagerRouterContent
		};
	});