define(['./arrows/@dir', './editor/@dir', 'text!./back.svg', 'text!./close.svg', 'text!./collapse.svg', 'text!./collapseall.svg', 'text!./copy.svg', 'text!./create.svg', 'text!./dropin.svg', 'text!./dropinall.svg', 'text!./dropout.svg', 'text!./dropoutall.svg', 'text!./downdouble.svg', 'text!./edit.svg', 'text!./expand.svg', 'text!./expandall.svg', 'text!./forth.svg', 'text!./help.svg', 'text!./history.svg',
	'text!./leftdouble.svg', 'text!./lots.svg', 'text!./move.svg', 'text!./pay.svg', 'text!./refresh.svg', 'text!./remove.svg', 'text!./rightdouble.svg', 'text!./send.svg', 'text!./surcharge.svg', 'text!./tags.svg', 'text!./transactions.svg', 'text!./undo.svg', 'text!./updouble.svg'],
	function(arrows, editor, back, close, collapse, collapseall, copy, create, dropin, dropinall, dropout, dropoutall, downdouble, edit, expand, expandall, forth, help, history, leftdouble, lots, move, pay, refresh, remove, rightdouble, send, surcharge, tags, transactions, undo, updouble) {
		return {
			arrows: arrows,
			editor: editor,
			back: back,
			close: close,
			collapse: collapse,
			collapseDown: collapseall,
			copy: copy,
			create: create,
			downdouble: downdouble,
			dropin: dropin,
			distribute: dropout,
			distributeall: dropoutall,
			edit: edit,
			expand: expand,
			expandDown: expandall,
			forth: forth,
			help: help,
			history: history,
			leftdouble: leftdouble,
			lots: lots,
			moveBranch: move,
			pay: pay,
			refresh: refresh,
			remove: remove,
			removeBranch: remove,
			rightdouble: rightdouble,
			send: send,
			surcharge: surcharge,
			tags: tags,
			transactions: transactions,
			undistribute: undo,
			undo: undo,
			updouble: updouble
		};
	});